// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfqbzahcphndfvedozsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmcWJ6YWhjcGhuZGZ2ZWRvenNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDMzMTIsImV4cCI6MjA2NTMxOTMxMn0.GEtkXyI63qf0lkE1ol79_aG7_KE5G8p4jzIWIKqzHbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);